Repository gardener/documentation, pull requests merged in 2020-12, with the labels that each got.

#156 Style Guide Update
  website/documentation/contribute/20_documentation/20_style/_index.md
Labels: size/m

#174 Add: create alibaba shoots
  website/documentation/guides/administer_shoots/gardener-alibaba/_index.md
  website/documentation/guides/administer_shoots/gardener-alibaba/images/Alibaba---Create-Custom-Policy.png
  website/documentation/guides/administer_shoots/gardener-alibaba/images/Alibaba---Create-Technical-User.png
  website/documentation/guides/administer_shoots/gardener-alibaba/images/Alibaba---Grant-Permissions.png
  website/documentation/guides/administer_shoots/gardener-alibaba/images/Alibaba-Cloud---copy-required-policies-from-Gardener-dashboard.png
  website/documentation/guides/administer_shoots/gardener-alibaba/images/Copy-icon.png
  website/documentation/guides/administer_shoots/gardener-alibaba/images/Create-new-project-in-Gardener.png
  website/documentation/guides/administer_shoots/gardener-alibaba/images/Gardener---Add-Alibaba-Cloud-Secret.png
  website/documentation/guides/administer_shoots/gardener-alibaba/images/Gardener---Assign-Alibaba-Cloud-Secret.png
  website/documentation/guides/administer_shoots/gardener-alibaba/images/Help-icon.png
Labels: reviewed/lgtm, size/s

#183 Adding: IDP Tutorial
  website/documentation/tutorials/oidc-login/Basic-information.png
  website/documentation/tutorials/oidc-login/Choose-application-type.png
  website/documentation/tutorials/oidc-login/Configure-callback.png
  website/documentation/tutorials/oidc-login/Create-client-application.png
  website/documentation/tutorials/oidc-login/Create-user.png
  website/documentation/tutorials/oidc-login/Login-through-identity-provider.png
  website/documentation/tutorials/oidc-login/_index.md
Labels: needs/changes, size/m

#188 Adds T-Systems as adopter
  website/adopter/_index.md
  website/adopter/images/tsystems.png
Labels: reviewed/lgtm, size/xs
