Repository gardener/documentation, pull requests merged in 2020-11, with the labels that each got.

#150 Add blog post about g/g v1.11/v1.12
  website/blog/2020-11/_index.md
Labels: needs/changes, size/s

#155 Fix links
  website/documentation/guides/administer_shoots/dns_names/_index.md
  website/documentation/guides/administer_shoots/dns_providers/_index.md
  website/documentation/guides/install_gardener/gardener_certificate_management/_index.md
Labels: needs/review, size/xs

#151 structure update
  .docforge/concepts.yaml
  .docforge/contribute.yaml
  .docforge/documentation.yaml
  .docforge/guides.yaml
  .docforge/references.yaml
  .docforge/tutorials.yaml
  .docforge/website.yaml
  documentation.yaml
  website/adopter/_index.md
  website/blog/2018_week_17/_index.md
  website/blog/2018_week_22/_index.md
  website/blog/2018_week_27/_index.md
  website/blog/2018_week_40/_index.md
  website/blog/2018_week_46/_index.md
  website/blog/2018_week_50/_index.md
  website/blog/2018_week_51/_index.md
  website/blog/2019_week_02/_index.md
  website/blog/2019_week_06/_index.md
  website/blog/2020_week_20/00.md
  website/community/_index.md
Labels: component/documentation, needs/second-opinion, size/xl

#163 change expiry date of a release blog due to newer releases
  website/blog/2020-09/_index.md
Labels: area/documentation, needs/review

#162 Adding a blog post from metal-stack on Gardener ETCD volume migration.
  website/blog/2020-11/00/_index.md
  website/blog/2020-11/01/01-001.svg
  website/blog/2020-11/01/_index.md
Labels: reviewed/lgtm, size/m

#165 update of hibernation doc
  website/documentation/guides/administer_shoots/hibernate-cluster/_index.md
  website/documentation/guides/administer_shoots/hibernate-cluster/images/Hibernate-Cluster.png
  website/documentation/guides/administer_shoots/hibernate-cluster/images/Hibernation-Schedule.png
  website/documentation/guides/administer_shoots/hibernate-cluster/images/Hibernation-Status.png
  website/documentation/guides/administer_shoots/hibernate-cluster/images/Wake-up-Cluster.png
  website/documentation/guides/administer_shoots/hibernate-cluster/slider/slide_1.png
  website/documentation/guides/administer_shoots/hibernate-cluster/slider/slide_2.png
  website/documentation/guides/administer_shoots/hibernate-cluster/slider/slide_3.png
  website/documentation/guides/administer_shoots/hibernate-cluster/slider/slide_4.png
  website/documentation/guides/administer_shoots/hibernate-cluster/slider/slide_5.png
Labels: reviewed/lgtm, size/s

#169 Change site-relative links to absolute
  website/adopter/_index.md
  website/adopter/images/beezlab.png
  website/adopter/images/bnerd.png
  website/adopter/images/fits.png
  website/adopter/images/pingcap.jpeg
  website/adopter/images/pingcap.png
  website/adopter/images/sap.png
  website/adopter/images/scaleup.png
  website/adopter/images/teaser.sketch
  website/adopter/images/teaser.svg
  website/blog/2020-05/00/_index.md
  website/blog/2020-10/00/_index.md
  website/blog/2020-11/01/_index.md
  website/community/_index.md
Labels: size/s

#170 Update organization and markup guides
  website/documentation/contribute/20_documentation/10_organisation/_index.md
  website/documentation/contribute/20_documentation/25_markup/_index.md
  website/documentation/contribute/20_documentation/25_markup/attachments.files/BachGavotteShort.mp3
  website/documentation/contribute/20_documentation/25_markup/attachments.files/Carroll_AliceAuPaysDesMerveilles.pdf
  website/documentation/contribute/20_documentation/25_markup/attachments.files/adivorciarsetoca00cape.pdf
  website/documentation/contribute/20_documentation/25_markup/attachments.files/hugo.png
  website/documentation/contribute/20_documentation/25_markup/attachments.files/movieselectricsheep-flock-244-32500-2.mp4
  website/documentation/contribute/20_documentation/25_markup/attachments.md
  website/documentation/contribute/20_documentation/25_markup/button.md
  website/documentation/contribute/20_documentation/25_markup/expand.md
  website/documentation/contribute/20_documentation/25_markup/mermaid.md
  website/documentation/contribute/20_documentation/25_markup/notice.md
  website/documentation/contribute/20_documentation/_index.md
Labels: reviewed/lgtm, size/l

#175 use template for the website.yaml
  .docforge/website.yaml
Labels: reviewed/lgtm, size/xs

#172 Add Gardener v1.13 release blog
  website/blog/2020-11/02/_index.md
Labels: needs/changes, size/s

#176 prepare for release of v1.12.8
  .docforge/website.yaml
Labels: reviewed/lgtm, size/xs

#177 use template version variable where possible
  .docforge/website.yaml
Labels: needs/review, size/xs

#179 update contributors guide front page to match CONTRIBUTORS
  website/documentation/contribute/_index.md
Labels: reviewed/lgtm, size/s

#178 rewrite links with version only for documentation
  .docforge/website.yaml
Labels: reviewed/lgtm, size/xs

#114 added STACKIT quote for Gardener
  website/adopter/_index.md
  website/adopter/images/stackit.png
Labels: needs/changes, size/xs
