Repository gardener/documentation, pull requests merged in 2020-10, with the labels that each got.

#141 Add KubeVirt blog
  .gitignore
  website/blog/2020-10/00/00-001.png
  website/blog/2020-10/00/00-002.png
  website/blog/2020-10/00/00-003.png
  website/blog/2020-10/00/00-004.png
  website/blog/2020-10/00/_index.md
Labels: reviewed/lgtm, size/m

#142 upgrade website-generator image version to 10.0.2
  scripts/serve
Labels: component/documentation, reviewed/lgtm, size/s

#138 Add blogpost 2020-10/00
  website/blog/2020-10/01/_index.md
Labels: size/m

#145 adding properties for api-references
  documentation.yaml
Labels: component/documentation, size/xs
