Repository gardener/documentation, pull requests merged in 2021-07, with the labels that each got.

#250 Update/Correct links
  website/community/_index.md
Labels: kind/enhancement, reviewed/lgtm, size/xs

#251 Rename index.md to _index.md to fix page name in the navigation
  website/documentation/guides/administer_shoots/gardener_azure/_index.md
Labels: kind/bug, reviewed/lgtm, size/xs

#252 Add Front Matter to update title
  website/documentation/guides/administer_shoots/gardener_azure/_index.md
Labels: needs/review, size/xs

#256 Fixed broken link
  website/blog/2020-09/Gardener-v1.9-and-v1.10-Released.md
Labels: needs/review, size/xs

#257 Fixed links
  website/blog/2020-11/02/Gardener-v1.13-Released.md
Labels: needs/review, size/xs

#258 Fixed links
  website/adopter/_index.md
Labels: needs/review, size/xs

#259 Fixed links
  website/blog/2020-05/00/PingCAPs-Experience.md
Labels: needs/review, size/xs

#260 Fixed links
  website/blog/2020-11/01/Case-Study-Migrating-ETCD-Volumes-in-Production.md
Labels: needs/review, size/xs

#261 Fixed links
  website/documentation/guides/install_gardener/setup-seed/_index.md
Labels: needs/review, size/xs

#262 Fixed links
  website/documentation/tutorials/knative-install/_index.md
Labels: needs/review, size/xs

#263 Fixed links
  website/documentation/tutorials/shoot_istio_dns_certs/_index.md
Labels: needs/review, size/xs

#264 Remove Bouquet addon page
  .docforge/concepts.yaml
Labels: reviewed/lgtm, size/xs

#265 Use a generic regex for downloads scope
  .docforge/concepts.yaml
Labels: reviewed/lgtm, size/xs

#269 Update _index.md
  website/documentation/tutorials/shoot_istio_dns_certs/_index.md
Labels: reviewed/lgtm, size/xs

#268 Update _index.md
  website/documentation/tutorials/knative-install/_index.md
Labels: reviewed/lgtm, size/xs

#267 Update _index.md
  website/documentation/guides/applications/access_pod_from_local/_index.md
Labels: reviewed/lgtm, size/xs

#266 Update _index.md
  website/documentation/contribute/10_code/30_deploy_seed_into_aks/_index.md
Labels: reviewed/lgtm, size/xs
