Repository gardener/documentation, pull requests merged in 2021-02, with the labels that each got.

#203 Remove installer app from website
  website/installer/_index.html
  website/installer/css/app.27ddd293.css
  website/installer/css/chunk-vendors.add15163.css
  website/installer/favicon.ico
  website/installer/js/app.55e1a531.js
  website/installer/js/app.55e1a531.js.map
  website/installer/js/chunk-vendors.c9e0454a.js
  website/installer/js/chunk-vendors.c9e0454a.js.map
Labels: needs/review, size/s

#199 Add Gardener anniversary blog post
  website/blog/2021-01/01/_index.md
  website/blog/2021-01/01/images/01.png
  website/blog/2021-01/01/images/02.png
  website/blog/2021-01/01/images/03.png
Labels: reviewed/lgtm, size/m

#204 Added publish date to Gardener anniversary blog
  website/blog/2021-01/01/_index.md
Labels: needs/review, size/xs

#206 Added YT link to the OOT MCM presentation
  website/blog/2021-01/00/_index.md
Labels: needs/review, size/xs

#211 adopter: added mercedes-benz.io
  website/adopter/_index.md
  website/adopter/images/mercedesbenzio.png
Labels: reviewed/lgtm, size/xs

#213 fix FM property type:doc->docs
  .docforge/concepts.yaml
Labels: needs/review

#214 Revert "adopter: added mercedes-benz.io"
  website/adopter/_index.md
  website/adopter/images/mercedesbenzio.png
Labels: needs/review, size/s

#212 Update helm charts and RBAC links
  website/documentation/guides/client_tools/helm/_index.md
Labels: reviewed/lgtm, size/xs

#209 Remove duplicate "Authenticating with an Identity Provider"
  website/documentation/guides/client_tools/oidc-login/_index.md
  website/documentation/guides/client_tools/oidc-login/application.png
  website/documentation/guides/client_tools/oidc-login/callback.png
  website/documentation/guides/client_tools/oidc-login/login.png
  website/documentation/guides/client_tools/oidc-login/user.png
Labels: reviewed/lgtm, size/m
