Repository gardener/documentation, pull requests merged in 2021-01, with the labels that each got.

#195 List of Gardener Security Team members updated
  security-release-process.md
Labels: reviewed/lgtm, size/m

#198 Blog on Machine Controller Manager
  website/blog/2021-01/00/_index.md
  website/blog/2021-01/00/images/00.png
  website/blog/2021-01/00/images/01.png
Labels: reviewed/lgtm, size/s

#73 add documentation and ops guide to guidelines
  CONTRIBUTING.md
Labels: lifecycle/stale

#201 Incorporating Vasu's suggestions
  website/blog/2021-01/00/_index.md
Labels: needs/changes, needs/review, size/s

#202 Correcting the wrong URLs
  website/blog/2021-01/00/_index.md
Labels: needs/review, size/xs
