Repository gardener/documentation, pull requests merged in 2021-04, with the labels that each got.

#223 Add guidelines for contributing bigger changes to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: merge/squash, reviewed/lgtm, size/xs

#218 Fix the link to the repository of the adopter page
  website/adopter/_index.md
Labels: needs/review, size/xs

#233 Use "Architecture" file from gardener/gardener repository
  .docforge/concepts.yaml
Labels: reviewed/lgtm, size/xs
