Repository gardener/documentation, pull requests merged in 2021-11, with the labels that each got.

#290 Restructure documentation
  .docforge/concepts.yaml
  .docforge/contribute.yaml
  .docforge/documentation.yaml
  .docforge/guides.yaml
  .docforge/references.yaml
  .docforge/tutorials.yaml
  .docforge/website.yaml
Labels: needs/rebase, needs/review, needs/second-opinion, size/xl

#291 Updated documentation description
  .docforge/documentation.yaml
Labels: needs/review, size/xs

#293 Fixed broken links
  website/blog/2020-11/01/Case-Study-Migrating-ETCD-Volumes-in-Production.md
Labels: needs/review, size/xs

#292 Add extensions in the documentation structure
  .docforge/documentation/contribute.yaml
  .docforge/documentation/documentation.yaml
  .docforge/documentation/gardener-extensions/container-runtime.yaml
  .docforge/documentation/gardener-extensions/gardener-extensions.yaml
  .docforge/documentation/gardener-extensions/infrastructure.yaml
  .docforge/documentation/gardener-extensions/network.yaml
  .docforge/documentation/gardener-extensions/operating-system.yaml
  .docforge/documentation/gardener-extensions/others.yaml
  .docforge/documentation/other-components.yaml
Labels: needs/review, size/m

#295 Fix documentation path in the manifest
  .docforge/website.yaml
Labels: needs/review, size/xs

#297 Add check-manifest step in the PR checks
  .ci/check-manifest
  .ci/pipeline_definitions
Labels: needs/review, size/s

#299 Add PR trait
  .ci/pipeline_definitions
Labels: needs/review, size/xs

#300 Make check-manifest executable
  .ci/check-manifest
Labels: needs/review, size/xs

#301 Fix manifest path in the check-manifest
  .ci/check-manifest
Labels: needs/review, size/xs

#302 Add check-manifest step in Makefile
  .ci/check-manifest
  Makefile
Labels: needs/review, size/xs

#304 Use org variable
  .ci/check-manifest
  .ci/check-manifest-config
  .docforge/documentation/contribute.yaml
  .docforge/documentation/documentation.yaml
  .docforge/documentation/gardener-extensions/container-runtime.yaml
  .docforge/documentation/gardener-extensions/gardener-extensions.yaml
  .docforge/documentation/gardener-extensions/infrastructure.yaml
  .docforge/documentation/gardener-extensions/network.yaml
  .docforge/documentation/gardener-extensions/operating-system.yaml
  .docforge/documentation/gardener-extensions/others.yaml
  .docforge/documentation/other-components.yaml
  .docforge/website.yaml
Labels: needs/review, size/m

#305 Remove set -u flag from the check-manifet script
  .ci/check-manifest
Labels: needs/review, size/xs

#307 Fix check-manifest duplicates
  .ci/check-manifest-config
Labels: needs/review

#308 Replace hardoced org with PR_ORG
  .ci/check-manifest
  .ci/check-manifest-config
Labels: needs/review, size/xs

#309 Add debug messages in the manifest script
  .ci/check-manifest
  .ci/check-manifest-config
Labels: needs/review

#310 Use gardener org for cross repo manifests
  .ci/check-manifest
  .ci/check-manifest-config
  .docforge/documentation/documentation.yaml
  .docforge/documentation/gardener-extensions/container-runtime.yaml
  .docforge/documentation/gardener-extensions/infrastructure.yaml
  .docforge/documentation/gardener-extensions/network.yaml
  .docforge/documentation/gardener-extensions/operating-system.yaml
  .docforge/documentation/gardener-extensions/others.yaml
  .docforge/documentation/other-components.yaml
Labels: needs/review, size/s

#311 Add cache for the check-manifest ci step
  .ci/check-manifest
  .ci/pipeline_definitions
Labels: needs/review

#312 Change cache dir
  .ci/check-manifest
Labels: needs/review, size/xs

#313 Switch to stable image for the check-manifest step
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#314 Add resoruce mapping in the check-manifest
  .ci/check-manifest
  .ci/check-manifest-config
  .docforge/documentation/contribute.yaml
  .docforge/documentation/documentation.yaml
  .docforge/documentation/gardener-extensions/gardener-extensions.yaml
  .docforge/website.yaml
Labels: needs/review

#316 Run check-manifest script only if there is diff in the documentation
  .ci/check-manifest
  .ci/pipeline_definitions
  Makefile
Labels: needs/review

#317 Add debugs in the check-manifest script
  .ci/check-manifest
Labels: needs/review

#318 Use repo path for git
  .ci/check-manifest
Labels: needs/review

#320 Add delimeter in the check-manifest script for diffDirs
  .ci/check-manifest
  .ci/check-manifest-entrypoint
Labels: needs/review, size/xs

#321 Remove test-manifest duplications due to token
  .ci/check-manifest
Labels: needs/review
