Repository gardener/documentation, pull requests merged in 2021-08, with the labels that each got.

#270 Fix node name collisions
  .docforge/guides.yaml
Labels: reviewed/lgtm, size/xs

#254 Removing obsolete & duplicate resources
  .docforge/documentation.yaml
  website/documentation/guides/_index.md
  website/documentation/guides/administer_shoots/trigger-shoot-operations/_index.md
  website/documentation/guides/applications/https/_index.md
  website/documentation/guides/install_gardener/landscape-setup/_index.md
  website/documentation/tutorials/_index.md
Labels: reviewed/lgtm, size/xl

#272 Remove custom short codes
  website/documentation/060-curated-links/_index.md
  website/documentation/contribute/10_code/_index.md
  website/documentation/guides/administer_shoots/maintain-shoot/_index.md
  website/documentation/guides/applications/insecure-configuration/_index.md
  website/documentation/tutorials/shoot_istio_dns_certs/_index.md
Labels: reviewed/lgtm, size/m
