Repository gardener/documentation, pull requests merged in 2022-08, with the labels that each got.

#359 Update Community Page
  website/community/_index.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#360 Remove non-Gardener related documentation from website
  website/documentation/guides/applications/access_pod_from_local/_index.md
  website/documentation/guides/applications/service-access/_index.md
Labels: needs/ok-to-test, reviewed/lgtm, size/l

#361 Provide meeting details for cilium presentation
  website/community/_index.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#362 Add plusserver as adopter
  website/adopter/_index.md
  website/adopter/images/plusserver.png
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#364 links now open english versions of the sites
  website/adopter/_index.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#365 "submit a pull request" link in Adopters page is fixed
  website/adopter/_index.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#363 Added blog posts
  website/blog/2022-02/00/Gardener-Community-Meeting-February.md
  website/blog/2022-08/00/Gardener-Community-Meeting-July-News.md
  website/community/_index.md
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#366 Updated links to point at English websites
  website/adopter/_index.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#367 Ambiguous argument origin/master fix
  .ci/check-manifest
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#368 Usage of token map in check-manifest
  .ci/check-manifest
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#372 Show master diff
  .ci/check-manifest
Labels: reviewed/ok-to-test

#373 Add origin of the source repo if not exist
  .ci/check-manifest
Labels: needs/ok-to-test
