Repository gardener/documentation, pull requests merged in 2022-02, with the labels that each got.

#325 Fixed broken links 01.2022
  website/blog/2018_week_40/Hibernate-a-Cluster-to-save-money.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#324 Updated Contribute section
  website/archived/contribute/code/13_env/_index.md
  website/archived/contribute/code/15_conf_secrets/_index.md
  website/archived/contribute/code/27_deploy_into_cluster/_index.md
  website/archived/contribute/code/30_deploy_seed_into_aks/_index.md
  website/archived/contribute/code/37_process/_index.md
  website/documentation/contribute/10_code/10-contribution_guide/_index.md
  website/documentation/contribute/10_code/10_contributing_bigger_changes/_index.md
  website/documentation/contribute/10_code/12_security_guide/_index.md
  website/documentation/contribute/10_code/20_dependencies/_index.md
  website/documentation/contribute/10_code/40_repositories/_index.md
  website/documentation/contribute/20_documentation/10_organisation/_index.md
  website/documentation/contribute/20_documentation/30_shortcodes/_index.md
  website/documentation/contribute/30_community/_index.md
  website/documentation/contribute/_index.md
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#329 Updated shortcode documentation
  website/documentation/contribute/20_documentation/30_shortcodes/_index.md
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#330 Update mermaid short code
  website/documentation/contribute/20_documentation/30_shortcodes/_index.md
Labels: needs/ok-to-test, needs/review, size/s
