Repository gardener/documentation, pull requests merged in 2022-05, with the labels that each got.

#348 Consolidate DL
  security-release-process.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#350 Added a style guide
  website/documentation/contribute/20_documentation/20_formatting_guide/_index.md
  website/documentation/contribute/20_documentation/40_style_guide/_index.md
  website/documentation/contribute/20_documentation/40_style_guide/concept_template.md
  website/documentation/contribute/20_documentation/40_style_guide/reference_template.md
  website/documentation/contribute/20_documentation/40_style_guide/task_template.md
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#351 Fixed broken link in the style guide
  website/documentation/contribute/20_documentation/40_style_guide/_index.md
Labels: needs/ok-to-test, needs/review, size/xs

#347 Add shoot-networking-filter extension manifest
  .docforge/documentation/gardener-extensions/others.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
