Repository gardener/documentation, pull requests merged in 2023-12, with the labels that each got.

#451 Added the rest of the STIGs
  website/documentation/guides/compliance/_index.md
  website/documentation/guides/compliance/kubernetes-hardening/_index.md
  website/documentation/guides/security-and-compliance/_index.md
  website/documentation/guides/security-and-compliance/kubernetes-hardening/_index.md
  website/documentation/guides/security-and-compliance/regional-restrictions/_index.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#452 Add audit rules to k8s hardening
  website/documentation/guides/security-and-compliance/kubernetes-hardening/_index.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#453 Remove two obsolete guides
  website/documentation/guides/client-tools/helm/_index.md
  website/documentation/guides/client-tools/kubectl-apiserver/_index.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#455 Minor Getting Started section changes
  website/documentation/getting-started/_index.md
  website/documentation/getting-started/ca-components/_index.md
  website/documentation/getting-started/introduction/_index.md
Labels: needs/ok-to-test, needs/review, size/xs

#454 gardenlogin should be used to transparently handle authentication
  website/documentation/getting-started/shoots/_index.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#456 Updated Getting Started section - 2023.12
  .docforge/documentation/documentation.yaml
  .docforge/documentation/faq.yaml
  .docforge/website.yaml
  website/documentation/contribute/_index.md
  website/documentation/getting-started/_index.md
  website/documentation/getting-started/ca-components/_index.md
  website/documentation/getting-started/features/certificate-management.md
  website/documentation/getting-started/features/credential-rotation.md
  website/documentation/getting-started/features/workerless-shoots.md
  website/documentation/getting-started/observability/_index.md
  website/documentation/getting-started/observability/alerts.md
  website/documentation/getting-started/observability/components.md
  website/documentation/getting-started/observability/shoot-status.md
  website/documentation/getting-started/shoots/_index.md
  website/documentation/glossary/_index.md
  website/documentation/resources/_index.md
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#457 Fix minor typos
  website/documentation/getting-started/introduction/_index.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#458 Fix minor typo
  website/documentation/getting-started/architecture/_index.md
Labels: needs/ok-to-test, needs/review, reviewed/lgtm, size/xs

#459 Fix a minor typo
  website/documentation/getting-started/project/_index.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
