Repository gardener/documentation, pull requests merged in 2023-10, with the labels that each got.

#435 Minor change
  .docforge/documentation/documentation.yaml
  website/documentation/contribute/_index.md
Labels: needs/ok-to-test, needs/review, size/xs

#436 Minor change
  .docforge/documentation/documentation.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#437 Add docs _index.md
  .docforge/website.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#438 Minor fix
  .docforge/documentation/gardener-extensions/gardener-extensions.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#433 Moved FAQ containing internal link
  website/documentation/faq/dynatrace.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#440 Add temporary persona when absent
  .docforge/documentation/documentation.yaml
  website/documentation/contribute/_index.md
  website/documentation/glossary/_index.md
  website/documentation/resources/_index.md
Labels: needs/ok-to-test, needs/review, size/xs
