Repository gardener/documentation, pull requests merged in 2023-11, with the labels that each got.

#439 Fix broken links - 2023.10
  website/adopter/_index.md
  website/blog/2022/06.17-Gardener-Community-Meeting-June.md
  website/documentation/faq/configure-worker-pools.md
  website/documentation/resources/curated-links/_index.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#441 Added Kubernetes Hardening security guide
  website/documentation/guides/kubernetes-hardening/_index.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#442 Minor Fix in Kubernetes Hardening Guide
  website/documentation/guides/kubernetes-hardening/_index.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#443 Add more extensions
  .docforge/documentation/gardener-extensions/others.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#444 Updated Contributor's Guide and added topic about updating the manifest
  website/documentation/contribute/_index.md
  website/documentation/contribute/documentation/adding-existing-documentation/_index.md
  website/documentation/contribute/documentation/style-guide/_index.md
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#445 Add dual-stack documentation for AWS
  .docforge/documentation/guides.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#446 Removed persona
  website/documentation/guides/kubernetes-hardening/_index.md
Labels: needs/ok-to-test, needs/review, size/xs

#447 add initial guide of the Conversion Webhook check
  website/documentation/guides/administer-shoots/conversion-webhook/_index.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#448 Added Regional Restrictions guide
  website/documentation/guides/compliance/_index.md
  website/documentation/guides/compliance/kubernetes-hardening/_index.md
  website/documentation/guides/compliance/regional-restrictions/_index.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#450 Cleaned up topics
  website/documentation/guides/compliance/kubernetes-hardening/_index.md
  website/documentation/guides/compliance/regional-restrictions/_index.md
Labels: needs/ok-to-test, needs/review, size/xs
