Repository gardener/documentation, pull requests merged in 2023-04, with the labels that each got.

#404 Update 10.20-Gardener-Community-Meeting-October-2.md - fix typo
  website/blog/2022/10.20-Gardener-Community-Meeting-October-2.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#405 Add guide on node failure analysis
  website/documentation/guides/monitoring_and_troubleshooting/analysing-node-failures/_index.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#408 Minor docs cleanup
  website/documentation/faq/gardener-locally.md
  website/documentation/guides/administer_shoots/gpu/_index.md
  website/documentation/guides/administer_shoots/gpu/images/howto-gpu.png
  website/documentation/guides/administer_shoots/oidc-login/_index.md
  website/documentation/guides/administer_shoots/oidc-login/images/Basic-information.png
  website/documentation/guides/administer_shoots/oidc-login/images/Choose-application-type.png
  website/documentation/guides/administer_shoots/oidc-login/images/Configure-callback.png
  website/documentation/guides/administer_shoots/oidc-login/images/Create-client-application.png
  website/documentation/guides/administer_shoots/oidc-login/images/Create-user.png
  website/documentation/guides/administer_shoots/oidc-login/images/Login-through-identity-provider.png
  website/documentation/guides/applications/dynamic-pvc/_index.md
  website/documentation/guides/applications/knative-install/_index.md
  website/documentation/guides/applications/knative-install/images/gardener_addon_checkboxes.png
  website/documentation/guides/applications/knative-install/images/gardener_service_account.png
  website/documentation/guides/applications/knative-install/images/gardener_shoot_creation.png
  website/documentation/guides/install_gardener/_index.md
  website/documentation/guides/install_gardener/add-node-to-cluster/_index.md
  website/documentation/guides/install_gardener/add-node-to-cluster/images/teaser.sketch
  website/documentation/guides/install_gardener/add-node-to-cluster/images/teaser.svg
  website/documentation/guides/install_gardener/secure-setup/_index.md
  website/documentation/guides/install_gardener/setup-seed/_index.md
  website/documentation/tutorials/_index.md
Labels: needs/review, needs/second-opinion, reviewed/ok-to-test, size/l

#409 Add information on scheduled events (VM terminations)
  website/documentation/guides/monitoring_and_troubleshooting/analysing-node-failures/_index.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
