Repository gardener/documentation, pull requests merged in 2023-05, with the labels that each got.

#411 Deleted temporary file - Restructure fix
  website/documentation/guides/monitoring_and_troubleshooting/analysing-node-failures/_index.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#412 Add Gardener scalability guide
  website/documentation/guides/administer-shoots/scalability/_index.md
  website/documentation/guides/administer-shoots/scalability/images/pod-nodes.png
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#413 Fixed broken links
  website/blog/2018/06.11-Kubernetes-is-available-in-Docker-for-Mac-17-12-CE.md
  website/blog/2019/06.11-Organizing-Access-Using-kubeconfig-Files.md
  website/documentation/guides/applications/prometheus/_index.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
