Repository gardener/documentation, pull requests merged in 2024-07, with the labels that each got.

#509 Fixed broken links - 2024.07
  website/adopter/_index.md
  website/documentation/resources/curated-links/_index.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#514 Fix check manifest entrypoint
  .ci/check-manifest-entrypoint
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#516 Remove check manifest
  .ci/check-manifest-entrypoint
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#513 Update the file structure of the Contribute section
  website/documentation/contribute/_index.md
  website/documentation/contribute/code/cicd.md
  website/documentation/contribute/code/contributing-bigger-changes.md
  website/documentation/contribute/code/dependencies.md
  website/documentation/contribute/code/images/cicd-overview.png
  website/documentation/contribute/code/images/cicd-overview.sketch
  website/documentation/contribute/documentation/adding-existing-documentation.md
  website/documentation/contribute/documentation/formatting-guide.md
  website/documentation/contribute/documentation/images.md
  website/documentation/contribute/documentation/markup.md
  website/documentation/contribute/documentation/organization.md
  website/documentation/contribute/documentation/pr-description.md
  website/documentation/contribute/documentation/shortcodes.md
  website/documentation/contribute/documentation/style-guide/_index.md
Labels: reviewed/lgtm, size/s

#519 Update the file structure of the Resources and Security sections
  website/documentation/resources/curated-links.md
  website/documentation/security-and-compliance/kubernetes-hardening.md
  website/documentation/security-and-compliance/regional-restrictions.md
Labels: reviewed/lgtm, size/xs

#521 Updated security.yaml due to diverging Kubernetes Hardening guides in the public and internal websites
  .docforge/documentation/documentation.yaml
  .docforge/documentation/security-and-compliance.yaml
Labels: reviewed/lgtm, size/xs

#522 Fixed broken links - 2024.07-3
  website/documentation/contribute/documentation/images.md
Labels: reviewed/lgtm, size/xs

#523 Updated weights for the Security topics
  .docforge/documentation/security-and-compliance.yaml
  website/documentation/security-and-compliance/hardened-shoot-report/hardened_shoots_docu_report.md
  website/documentation/security-and-compliance/kubernetes-hardening.md
  website/documentation/security-and-compliance/regional-restrictions.md
Labels: reviewed/lgtm, size/xs

#524 Added Shoot Pod Autoscaling Best Practices guide to Applications section
  .docforge/documentation/guides.yaml
Labels: reviewed/lgtm, size/xs

#525 Removed duplicated guides - 2024.07
  .docforge/documentation/documentation.yaml
Labels: reviewed/lgtm, size/xs
