Repository gardener/documentation, pull requests merged in 2024-04, with the labels that each got.

#484 Fixed broken links - 2024.04
  website/archived/blog/2018/06.11-Frontend-HTTPS.md
  website/archived/blog/2019/06.11-Cluster-Overprovisioning.md
  website/documentation/contribute/_index.md
  website/documentation/guides/applications/prometheus/_index.md
  website/documentation/resources/curated-links/_index.md
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#486 Minor section reorder
  .docforge/documentation/documentation.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#487 Fixed broken links - 2024.04-2: remove gardener-extension-provider-vsphere from public site
  .docforge/documentation/gardener-extensions/infrastructure.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#490 Fix typos in docs
  website/documentation/getting-started/architecture/_index.md
  website/documentation/getting-started/introduction/_index.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#492 SpinKube on Gardener Shoot cluster blog post
  website/blog/2024/04-18-SpinKube-Gardener-Shoot-Cluster.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#493 Add diki partial DISA K8s STIG guide
  .docforge/documentation/guides.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#494 Minor typo in WASM blog
  website/blog/2024/04-18-SpinKube-Gardener-Shoot-Cluster.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#495 Add "Gardener's Registry Cache Extension: Another Cost Saving Win and More" blog post
  website/blog/2024/04-22-Gardener's-Registry-Cache-Extension:-Another-Cost-Saving-Win-and-More.md
  website/blog/2024/images/shoot-cluster-with-registry-cache.png
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#497 Add link to Registry Cache Extension
  website/blog/2024/04-22-Gardener's-Registry-Cache-Extension:-Another-Cost-Saving-Win-and-More.md
Labels: needs/ok-to-test, size/xs

#496 Rename Run DISA K8s STIGs guide
  .docforge/documentation/guides.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#498 Update Registry Cache blog
  website/blog/2024/04-22-Gardener's-Registry-Cache-Extension-Another-Cost-Saving-Win-and-More.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
