Repository gardener/documentation, pull requests merged in 2024-06, with the labels that each got.

#502 Updated Glossary persona to "Users"
  website/documentation/glossary/_index.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#504 Fix etcd druid manifest
  .docforge/documentation/other-components.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#505 Remove raw suffix
  website/documentation/contribute/code/cicd/_index.md
Labels: needs/ok-to-test, needs/review, size/xs

#506 Moved Security Content
  .docforge/documentation/documentation.yaml
  .docforge/documentation/guides.yaml
  .docforge/documentation/security-and-compliance.yaml
  website/documentation/guides/security-and-compliance/_index.md
  website/documentation/security-and-compliance/kubernetes-hardening/_index.md
  website/documentation/security-and-compliance/regional-restrictions/_index.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s
