Repository gardener/documentation, pull requests merged in 2024-03, with the labels that each got.

#477 Delete video due to link not working - 2024.03
  website/documentation/resources/videos/envoy-service-mesh.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#476 Added FAQ on how to add feature gates to a shoot cluster
  website/documentation/faq/add-feature-gates.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#479 Remove DEFAULT_BRANCH
  .docforge/documentation/documentation.yaml
  .docforge/documentation/gardener-extensions/container-runtime.yaml
  .docforge/documentation/gardener-extensions/infrastructure.yaml
  .docforge/documentation/gardener-extensions/network.yaml
  .docforge/documentation/gardener-extensions/operating-system.yaml
  .docforge/documentation/gardener-extensions/others.yaml
  .docforge/documentation/guides.yaml
  .docforge/documentation/other-components.yaml
  website/documentation/contribute/documentation/adding-existing-documentation/_index.md
Labels: needs/ok-to-test, needs/review, size/m

#480 Remove forgotten DEFAULT_BRANCH
  .docforge/documentation/documentation.yaml
  .docforge/documentation/gardener-extensions/others.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#483 Archived outdated blog post - 2024.03
  website/archived/blog/2019/06.11-Manually-Adding-a-Node-to-an-Existing-Cluster.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
