Repository gardener/documentation, pull requests merged in 2024-05, with the labels that each got.

#500 Removed brackets from Project topic
  website/documentation/getting-started/project/_index.md
Labels: needs/ok-to-test, needs/review, size/xs

#501 Describe howto access the shoot kubernetes apiserver via tailscale vpn
  website/documentation/guides/administer-shoots/tailscale/_index.md
  website/documentation/guides/administer-shoots/tailscale/tailscale.drawio.svg
Labels: needs/ok-to-test, reviewed/lgtm, size/l

#499 Removed Architecture folder from manifest due to move
  .docforge/documentation/documentation.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
