Repository gardener/documentation, pull requests merged in 2024-11, with the labels that each got.

#544 recommend GEP for bigger changes
  website/documentation/contribute/code/contributing-bigger-changes.md
Labels: needs/review, reviewed/lgtm, size/xs

#546 Add PromCon 2024 blog post
  website/blog/2024/11-06-PromCon-EU-2024-md
  website/blog/2024/images/promcon2024.jpeg
Labels: reviewed/lgtm, size/s

#548 Fix file name extension for PromCon blog post
  website/blog/2024/11-06-PromCon-EU-2024.md
Labels: needs/review, size/xs

#551 Fix unparsable publishdates
  .docforge/documentation/guides.yaml
Labels: reviewed/lgtm, size/xs

#539 Fixed broken links - 2024.10
  website/blog/2018/07.11-Hibernate-a-Cluster-to-save-money.md
  website/blog/2020/11.04-Gardener-v1.11-and-v1.12-Released.md
  website/blog/2023/03-27-High-Availability-and-Zone-Outage-Toleration.md
  website/blog/2024/04-18-SpinKube-Gardener-Shoot-Cluster.md
  website/documentation/getting-started/common-pitfalls.md
  website/documentation/getting-started/features/credential-rotation.md
  website/documentation/getting-started/lifecycle.md
  website/documentation/getting-started/observability/components.md
  website/documentation/getting-started/project.md
  website/documentation/getting-started/shoots.md
  website/documentation/guides/administer-shoots/maintain-shoot.md
  website/documentation/guides/administer-shoots/scalability.md
Labels: reviewed/lgtm, size/s

#552 Removed ZenHub section
  website/documentation/contribute/_index.md
Labels: reviewed/lgtm, size/xs

#553 Fixed "Analyzing Node Removal and Failures" file name
  website/documentation/guides/monitoring-and-troubleshooting/analyzing-node-failures.md
Labels: reviewed/lgtm, size/xs

#556 Adapt documentation for removal of automatic `.md` addition in `Docforge`
  .docforge/documentation/documentation.yaml
  .docforge/documentation/guides.yaml
  .docforge/documentation/other-components.yaml
Labels: reviewed/lgtm, size/xs
