Repository gardener/documentation, pull requests merged in 2025-03, with the labels that each got.

#582 Added Network Problem Detector documentation
  .docforge/documentation/other-components.yaml
Labels: needs/review, size/xs

#584 Updated manifest - 2025.03
  .docforge/documentation/other-components.yaml
Labels: reviewed/lgtm, size/xs

#571 Consolidated Resources section
  website/documentation/resources/_index.md
  website/documentation/resources/curated-links.md
  website/documentation/resources/videos/gardener-teaser.md
Labels: reviewed/lgtm, size/m

#585 Adjust OIDC guide to use structured authentication
  website/documentation/guides/administer-shoots/oidc-login.md
Labels: reviewed/lgtm, size/s

#586 Add community bio shortcode to community/_index.md
  website/community/_index.md
Labels: reviewed/lgtm, size/xs

#588 Added information on scaling recommender steering
  website/community/product-steering/_index.md
Labels: needs/review

#587 Updated control-plane-components image
  website/documentation/getting-started/observability/images/control-plane-components.png
Labels: reviewed/lgtm, size/xs

#591 Move important links (community bio) to separate page in community
  website/community/_index.md
  website/community/community-bio.md
Labels: reviewed/lgtm, size/xs

#590 Update observability 2.0 link
  website/community/technical-steering/_index.md
Labels: reviewed/lgtm, size/xs

#592 Rename Fuga Cloud to Cyso Cloud
  website/adopter/_index.md
  website/adopter/images/cyso-cloud-logo-transparent.png
  website/adopter/images/fuga-cloud-logo-blue-transparent.png
Labels: needs/review, reviewed/lgtm, size/xs

#593 Fixed cyso image name
  website/adopter/_index.md
Labels: needs/review, reviewed/lgtm, size/xs

#595 Added Gardener Extensions Library topic
  .docforge/documentation/documentation.yaml
Labels: reviewed/lgtm, size/xs

#597 Add Gardener KubeCon Europe Announcement
  website/blog/2025/03-18-Gardener-KubeCon-CloudNativeCon-Europe-2025-Announcement.md
Labels: reviewed/lgtm, size/s

#599 adopter: add exigo
  website/adopter/_index.md
  website/adopter/images/exigo.png
Labels: reviewed/lgtm, size/xs, status/closed

#596 Update product steering documentation after initial feedback.
  website/community/product-steering/_index.md
Labels: reviewed/lgtm, size/xs

#600 Update timebertt's email address
  website/community/product-steering/_index.md
  website/community/technical-steering/_index.md
Labels: needs/review, size/xs

#594 Product steering meeting on scaling recommender
  website/community/product-steering/_index.md
Labels: needs/changes, reviewed/lgtm, size/xs

#601 Update steering meeting procedures
  website/community/product-steering/_index.md
  website/community/technical-steering/_index.md
Labels: reviewed/lgtm, size/xs

#589 Replaced shortcodes
  website/archived/contribute/code/13_env/_index.md
  website/archived/contribute/code/15_conf_secrets/_index.md
  website/archived/contribute/code/27_deploy_into_cluster/_index.md
  website/archived/contribute/code/37_process/_index.md
  website/blog/2020/11.20-Case-Study-Migrating-ETCD-Volumes-in-Production.md
  website/community/_index.md
  website/documentation/contribute/code/dependencies.md
  website/documentation/contribute/documentation/adding-existing-documentation.md
  website/documentation/contribute/documentation/formatting-guide.md
  website/documentation/contribute/documentation/markup.md
  website/documentation/contribute/documentation/organization.md
  website/documentation/contribute/documentation/shortcodes.md
  website/documentation/getting-started/common-pitfalls.md
  website/documentation/getting-started/features/credential-rotation.md
  website/documentation/getting-started/observability/components.md
  website/documentation/getting-started/project.md
  website/documentation/getting-started/shoots.md
  website/documentation/guides/administer-shoots/backup-restore.md
  website/documentation/guides/administer-shoots/conversion-webhook.md
  website/documentation/guides/administer-shoots/create-shoot-into-existing-aws-vpc.md
  website/documentation/guides/administer-shoots/gpu.md
  website/documentation/guides/administer-shoots/maintain-shoot.md
  website/documentation/guides/administer-shoots/oidc-login.md
  website/documentation/guides/applications/access-pod-from-local.md
  website/documentation/guides/applications/commit-secret-fail.md
  website/documentation/guides/applications/missing-registry-permission.md
  website/documentation/guides/applications/network-isolation.md
  website/documentation/guides/applications/secure-seccomp.md
  website/documentation/guides/client-tools/bash-tips.md
Labels: reviewed/lgtm, size/l

#602 Observability 2.0 minutes & decision
  website/community/technical-steering/_index.md
Labels: reviewed/lgtm, size/xs

#598 Updated the Community and Bio pages
  website/community/_index.md
  website/community/community-bio.md
  website/community/product-steering/_index.md
  website/community/review-meetings/2022-reviews.md
  website/community/review-meetings/2023-reviews.md
  website/community/review-meetings/2024-reviews.md
  website/community/review-meetings/2025-reviews.md
  website/community/review-meetings/_index.md
  website/community/technical-steering/_index.md
Labels: reviewed/lgtm, size/xl
