Repository gardener/documentation, pull requests merged in 2025-05, with the labels that each got.

#617 Add Docforge `config.yaml`
  .docforge/config.yaml
Labels: reviewed/lgtm, size/xs

#616 Adapt website manifests for new Docforge version
  .docforge/adopters/adopters.yaml
  .docforge/documentation/documentation.yaml
  .docforge/documentation/gardener-extensions/gardener-extensions.yaml
  .docforge/documentation/other-components.yaml
  .docforge/website.yaml
  website/adopter/_index.md
  website/adopter/images/teaser.sketch
  website/blog/2018/12.22-Cookies-are-dangerous.md
Labels: reviewed/lgtm, size/xs

#618 Move pipeline definitions from gardener-website repo
  .ci/404.sh
  .ci/build
  .ci/pipeline_definitions
Labels: reviewed/lgtm, size/m

#619 Adapt pipeline definitions
  .ci/pipeline_definitions
Labels: needs/review, reviewed/lgtm, size/xs

#622 Add CNAME file generation to updated build script
  .ci/build
  .docforge/config.yaml
Labels: needs/review, size/xs

#626 Move website-generator docker branch related files
  .gitignore
  Dockerfile
  README.md
  compose.yaml.tpl
  package.json
Labels: needs/review, reviewed/lgtm, size/m

#621 Standardized the footer content
  website/hugo/layouts/partials/footer.html
Labels: reviewed/lgtm, size/xs

#623 Short blog on KubeCon talk with SIG Cluster API
  website/blog/2019/05.24-Cluster-API-Machine-Abstractions-KubeCon-Talk.md
Labels: reviewed/lgtm, size/xs

#627 Add basic automated testing with Selenium
  .ci/pipeline_definitions
  .ci/selenium-test.py
Labels: needs/review, size/m

#628 Introduce script for e2e testing
  .ci/e2e-test
  test/selenium-test.py
Labels: needs/review, size/xs

#624 Short blog on our security posture in the light of ACI attack
  website/blog/2021/09.12-Navigating-Cloud-Native-Security.md
Labels: reviewed/lgtm, size/s

#630 Introduce `make test`
  .ci/e2e-test
  .ci/pipeline_definitions
  Makefile
  README.md
  test/selenium-test.py
Labels: reviewed/lgtm, size/s

#631 Add automated trigger of build job on update of repo
  .ci/pipeline_definitions
Labels: needs/review, size/xs

#633 Manually change VERSION to v1.20.0-dev
  VERSION
Labels: needs/review, reviewed/lgtm, size/xs

#638 Add blog enhanced-network-flexibility-gardener-now-supports-cidr-overlap-for-non-ha-shoots
  website/blog/2025/05-19-enhanced-network-flexibility-gardener-now-supports-cidr-overlap-for-non-ha-shoots.md
Labels: reviewed/lgtm, size/s

#641 Add blog streamlined-node-onboarding-introducing-gardenadm-token-and-gardenadm-join
  website/blog/2025/05-21-streamlined-node-onboarding-introducing-gardenadm-token-and-gardenadm-join.md
Labels: reviewed/lgtm, size/s

#640 Add blog new-in-gardener-forceful-redeployment-of-gardenlets-for-enhanced-operational-control
  website/blog/2025/05-21-new-in-gardener-forceful-redeployment-of-gardenlets-for-enhanced-operational-control.md
Labels: needs/changes, size/s

#642 Add blog fine-tuning-kube-proxy-readiness-ensuring-accurate-health-checks-during-node-scale-down
  website/blog/2025/05-21-fine-tuning-kube-proxy-readiness-ensuring-accurate-health-checks-during-node-scale-down.md
Labels: reviewed/lgtm, size/s

#646 Consider only `.md` files in `404.sh`
  .ci/404.sh
Labels: needs/review, size/xs

#647 Moved blogs from May to correct folder
  website/blog/2025/05/05-19-enhanced-node-management-introducing-in-place-updates-in-gardener.md
  website/blog/2025/05/05-21-fine-tuning-kube-proxy-readiness-ensuring-accurate-health-checks-during-node-scale-down.md
  website/blog/2025/05/05-21-new-in-gardener-forceful-redeployment-of-gardenlets-for-enhanced-operational-control.md
Labels: needs/review, size/xs
