Repository gardener/documentation, pull requests merged in 2025-06, with the labels that each got.

#650 Update Docsy to v0.12.0 and Hugo to 0.147.7
  Dockerfile
  website/hugo/layouts/_default/_markup/render-heading.html
  website/hugo/layouts/_markup/render-heading.html
Labels: reviewed/lgtm, size/xs

#655 Improve `navbar.js` to use dynamic indexing
  website/hugo/static/js/navbar.js
Labels: reviewed/lgtm, size/xs

#613 Updated `Upgrading Kubernetes Versions` FAQ Page
  website/documentation/faq/automatic-upgrade.md
  website/documentation/faq/kubernetes-upgrade.md
Labels: reviewed/lgtm, size/s

#658 docs: Blog entry for the 7th Hack the Garden event
  website/blog/2025/06/06-17-Taking-Gardener-to-the-Next-Level-Highlights-from-the-7th-Gardener-Community-Hackathon-in-Schelklingen.md
  website/blog/2025/06/_index.md
  website/blog/2025/06/images/group-picture.png
Labels: reviewed/lgtm, size/m

#664 Updated the Contributors Guide
  website/documentation/contribute/documentation/adding-existing-documentation.md
  website/documentation/contribute/documentation/markup.md
  website/documentation/contribute/documentation/organization.md
  website/documentation/contribute/documentation/style-guide/_index.md
Labels: reviewed/lgtm, size/s

#657 Fixed broken links - 2025.06
  website/blog/2020/11.04-Gardener-v1.11-and-v1.12-Released.md
  website/blog/2025/04/04-17-Leaner-Clusters-Lower-Bills.md
  website/blog/2025/05/05-12-Gardener-NeoNephos.md
  website/community/review-meetings/2022-community.md
  website/community/review-meetings/2023-reviews.md
  website/hugo/layouts/index.html
Labels: needs/review, size/xs
