Repository gardener/documentation, pull requests merged in 2025-08, with the labels that each got.

#683 docs: Remove PingCAP references
  website/adopter/_index.md
  website/blog/2020/05.27-PingCAPs-Experience.md
  website/blog/2020/images/pingcap/00-001.png
  website/blog/2020/images/pingcap/00-002.png
  website/blog/2020/images/pingcap/00-003.png
  website/blog/2020/images/pingcap/00-004.png
  website/blog/2021/02.01-Happy-anniversary-Gardener.md
Labels: needs/review, size/s

#676 Add blog enhancing-data-protection-with-immutable-backup-buckets
  website/blog/2025/07/07-16-enhancing-data-protection-with-immutable-backup-buckets.md
Labels: reviewed/lgtm, size/m

#686 chore: Convert deprecated dep5 to REUSE.toml
  .reuse/dep5
  REUSE.toml
Labels: area/open-source, kind/enhancement, reviewed/lgtm, size/s

#688 Fix link in blogpost
  website/blog/2025/08/08-04-cluster-api-provider-gardener.md
Labels: needs/review, size/xs

#699 feat: Improve Dockerfile
  .docforge/config.yaml
  .dockerignore
  Dockerfile
  Dockerfile.dev
  Makefile
  README.md
  README.old.md
  compose.yaml.tpl
  hack/preview.sh
  scripts/run-hugo
  scripts/serve
  scripts/stop
Labels: needs/review, needs/second-opinion, size/l

#702 fix: Add trailing slash to sidebar links
  .vitepress/theme/blog-sidebar.ts
  .vitepress/theme/community-sidebar.ts
  .vitepress/theme/docs-sidebar.ts
  .vitepress/theme/utils/sidebar.ts
Labels: needs/review, reviewed/lgtm, size/s

#706 Added index.md in Infrastructure manifest
  .docforge/documentation/gardener-extensions/infrastructure.yaml
Labels: reviewed/lgtm, size/xs
