Repository gardener/documentation, pull requests merged in 2025-01, with the labels that each got.

#527 Adding more info in getting started section
  website/documentation/getting-started/architecture.md
  website/documentation/getting-started/ca-components.md
  website/documentation/getting-started/introduction.md
Labels: reviewed/lgtm, size/xs

#565 Add hugo.yaml
  .docforge/hugo.yaml
Labels: needs/review, size/xs

#566 Removed unused images
  website/documentation/getting-started/features/images/auditing.png
  website/documentation/getting-started/features/images/configure-audit-logs.png
Labels: reviewed/lgtm, size/xs

#568 fix: Update to new `CloudProfile` reference
  website/documentation/guides/administer-shoots/create-delete-shoot.md
  website/documentation/security-and-compliance/hardened-shoot-report/hardened_shoots_docu_report.md
Labels: needs/review, reviewed/lgtm

#567 Removed mentions of SAP from the documentation
  website/documentation/_index.html_
  website/documentation/contribute/documentation/images.md
  website/documentation/contribute/documentation/style-guide/_index.md
  website/documentation/getting-started/ca-components.md
  website/documentation/getting-started/introduction.md
  website/documentation/guides/applications/insecure-configuration.md
Labels: reviewed/lgtm, size/xs

#569 Fixed broken links - 2025.01
  website/documentation/faq/dns-config.md
  website/documentation/faq/rotate-iaas-keys.md
  website/documentation/guides/administer-shoots/scalability.md
Labels: reviewed/lgtm, size/xs
