Repository gardener/documentation, pull requests merged in 2025-07, with the labels that each got.

#661 Add blog gardener-enhances-observability-with-opentelemetry-integration-for-logging
  website/blog/2025/06-18-gardener-enhances-observability-with-opentelemetry-integration-for-logging.md
Labels: reviewed/lgtm, size/s

#674 [blog] Getting started with OpenTelemetry on a Gardener shoot cluster
  .gitignore
  website/blog/2025/06/06-30-getting-started-with-opentelemetry-on-gardener-shoot-cluster.md
  website/blog/2025/06/images/otel-gardener-shoot.png
  website/blog/2025/06/images/otel-mTLS-kube-rbac-proxy.png
  website/blog/2025/06/images/otel-prometheus.png
  website/blog/2025/06/images/otel-victoria-logs.png
  website/blog/2025/06/manifests/otel-collectors/k8s-events-otel.yaml
  website/blog/2025/06/manifests/otel-collectors/k8s-events-rbac.yaml
  website/blog/2025/06/manifests/otel-collectors/otel-certificate.yaml
  website/blog/2025/06/manifests/otel-collectors/shoot-metrics-otel.yaml
  website/blog/2025/06/manifests/otel-collectors/shoot-metrics-rbac.yaml
  website/blog/2025/06/manifests/otel-prometheus/certificate.yaml
  website/blog/2025/06/manifests/otel-prometheus/mtls-ra.yml
  website/blog/2025/06/manifests/otel-prometheus/mtls-rbac.yaml
  website/blog/2025/06/manifests/otel-prometheus/prometheus-config.yml
  website/blog/2025/06/manifests/otel-prometheus/prometheus.yaml
  website/blog/2025/06/manifests/otel-victorialogs/certificate.yaml
  website/blog/2025/06/manifests/otel-victorialogs/mtls-ra.yml
  website/blog/2025/06/manifests/otel-victorialogs/mtls-rbac.yaml
  website/blog/2025/06/manifests/otel-victorialogs/values.yaml
Labels: reviewed/lgtm, size/xl

#673 Move blogs - 2025.06
  website/blog/2025/06/06-18-enabling-seamless-ipv4-to-dual-stack-migration-for-kubernetes-clusters-on-gcp.md
  website/blog/2025/06/06-18-enhanced-extension-management-introducing-autoenable-and-clustercompatibility.md
  website/blog/2025/06/06-18-enhanced-internal-traffic-management-l7-load-balancing-for-kube-apiservers-in-gardener.md
  website/blog/2025/06/06-18-gardener-enhances-observability-with-opentelemetry-integration-for-logging.md
  website/blog/2025/06/06-25-enhancing-meltdown-protection-with-dependency-watchdog-annotations.md
  website/blog/2025/06/06-25-improving-credential-management-for-seed-backups.md
  website/blog/2025/06/06-30-getting-started-with-opentelemetry-on-gardener-shoot-cluster.md
  website/blog/2025/06/images/otel-mtls-kube-rbac-proxy.png
Labels: reviewed/lgtm, size/xs

#682 fix: Rewrite for trailing slashes
  .vitepress/config.mts
Labels: needs/review, size/xs
