Repository gardener/documentation, pull requests merged in 2025-09, with the labels that each got.

#684 Add blog enhanced-network-flexibility-cidr-overlap-now-supported-for-ha-shoots
  website/blog/2025/07/07-30-enhanced-network-flexibility-cidr-overlap-now-supported-for-ha-shoots.md
Labels: needs/review, size/s

#710 fix: Use new favicon set
  .docforge/config.yaml
  .vitepress/config.mts
  website/hugo/static/favicons/favicon-96x96.png
  website/hugo/static/favicons/favicon.ico
  website/public/apple-touch-icon.png
  website/public/favicon-96x96.png
  website/public/favicon.ico
  website/public/favicon.svg
  website/public/site.webmanifest
  website/public/web-app-manifest-192x192.png
  website/public/web-app-manifest-512x512.png
Labels: reviewed/lgtm, size/s

#714 Raise node and pod limits per cluster
  website/documentation/guides/administer-shoots/scalability.md
Labels: reviewed/lgtm, size/xs

#717 Fix: Test
  tests/sidebar-trunk-without-links.test.ts
Labels: needs/review, size/xs

#716 add documentation for gcp IPv6 support
  .docforge/documentation/guides.yaml
Labels: reviewed/lgtm, size/xs

#711 Add blog enabling-node-local-dns-without-node-rollouts
  website/blog/2025/08/08-27-enabling-node-local-dns-without-node-rollouts.md
Labels: reviewed/lgtm, size/s

#718 feat: Turn documentation in navbar into a link
  .vitepress/config.mts
  .vitepress/theme/components/VPNavbarMenuGroupWrapper.vue
  .vitepress/theme/index.ts
Labels: needs/review, size/s

#719 feat: Improve blog
  .vitepress/config.mts
  .vitepress/theme/blog-sidebar.ts
  website/blog/2025/06/06-25-enhanced-health-checks-for-node-rolling-updates.md
  website/blog/2025/06/06-25-introducing-gardenadm-bootstrap-for-autonomous-shoots.md
  website/blog/2025/07/_index.md
  website/blog/2025/08/_index.md
  website/blog/index.md
  website/blog/overview.md
Labels: needs/review, reviewed/lgtm, size/s

#724 Add blog explicit-internal-dns-configuration-for-seeds
  website/blog/2025/09/09-10-explicit-internal-dns-configuration-for-seeds.md
Labels: reviewed/lgtm, size/s

#712 Add blog new-emergency-brake-for-gardener-shoot-reconciliations
  website/blog/2025/08/08-27-new-emergency-brake-for-gardener-shoot-reconciliations.md
Labels: reviewed/lgtm, size/s

#723 Add blog modernizing-gardeners-logging-stack-with-opentelemetry
  website/blog/2025/09/09-10-modernizing-gardeners-logging-stack-with-opentelemetry.md
Labels: needs/review, size/s

#715 Gardener Community Roles
  website/documentation/contribute/code/roles/_index.md
Labels: reviewed/lgtm, size/s, area/ipcei
