Repository gardener/documentation, pull requests merged in 2025-04, with the labels that each got.

#604 Scaling recommender product steering update
  website/community/product-steering/_index.md
Labels: reviewed/lgtm, size/xs, status/closed

#609 replace committers with code owners
  website/community/technical-steering/_index.md
Labels: needs/review, reviewed/lgtm, size/xs

#607 Switch Slack references to Gardener workspace
  website/blog/2020/05.11-New-Website-Same-Green-Flower.md
  website/blog/2020/11.23-Gardener-v1.13-Released.md
  website/blog/2021/02.01-Happy-anniversary-Gardener.md
  website/community/_index.md
  website/documentation/contribute/_index.md
  website/documentation/contribute/documentation/organization.md
Labels: area/open-source, kind/enhancement, needs/review, reviewed/lgtm, size/xs

#608 Added ACL documentation and updated manifests - 2025.04
  .docforge/documentation/documentation.yaml
  .docforge/documentation/faq.yaml
  .docforge/documentation/gardener-extensions/gardener-extensions.yaml
  .docforge/documentation/gardener-extensions/others.yaml
  .docforge/documentation/other-components.yaml
  website/community/review-meetings/2025-reviews.md
  website/documentation/contribute/_index.md
  website/documentation/extensions/others/_index.md
  website/documentation/extensions/others/acl-extension.md
  website/documentation/getting-started/_index.md
  website/documentation/glossary/_index.md
  website/documentation/guides/administer-shoots/tailscale.md
  website/documentation/resources/_index.md
  website/documentation/security-and-compliance/_index.md
Labels: reviewed/lgtm, size/m

#611 Add blog about how we reduced operational costs
  website/blog/2025/04-17-Leaner-Clusters-Lower-Bills.md
Labels: needs/changes, needs/second-opinion, size/l

#614 Add newline to `<code> `block in formatting guide for consistent formatting
  website/documentation/contribute/documentation/formatting-guide.md
Labels: reviewed/lgtm, size/xs
