Repository gardener/documentation, pull requests merged in 2025-02, with the labels that each got.

#547 Updated Components topic for OIDC authentication
  website/documentation/getting-started/observability/components.md
  website/documentation/getting-started/observability/images/access-plutono-old.png
  website/documentation/getting-started/observability/images/access-plutono.png
Labels: reviewed/lgtm, size/xs

#575 Add steering meeting pages
  website/community/product-steering/_index.md
  website/community/technical-steering/_index.md
Labels: reviewed/lgtm, size/m

#573 Transfer frontmatter - 2025.02
  .docforge/documentation/other-components.yaml
Labels: reviewed/lgtm, size/s

#577 Make steering normal pages and not sections
  website/community/product-steering.md
  website/community/technical-steering.md
Labels: needs/review, size/xs

#580 Update product-steering.md
  website/community/product-steering.md
Labels: needs/review, size/xs

#579 Update technical-steering.md
  website/community/technical-steering.md
Labels: needs/review, size/xs

#581 Move community steering pages to directories
  website/community/product-steering/_index.md
  website/community/technical-steering/_index.md
Labels: reviewed/lgtm, size/xs
